#!/bin/bash
url="$(curl https://ncs.io/$1 | pup 'div[data-url] attr{data-url}' > tempfile342)"
extention=".$(cat tempfile342 | grep -Eo -- 'mp3|flac|wav|webm')"
downurl="$(cat tempfile342)"
echo"$(wget "$downurl" -O $1$extention)"
echo="$(rm -rf tempfile342)"
