#!/bin/bash
for i
do
    echo $i
    url="$(curl https://ncs.io/$i | pup 'div[data-url] attr{data-url}' > tempfile)"
    extention=".$(cat tempfile | grep -Eo -- 'mp3|flac|wav|webm')"
    downurl="$(cat tempfile)"
    echo"$(wget "$downurl" -O $i$extention)"
    echo="$(rm -rf tempfile)"
done
